export const url = {
  tokenName: 'progectManagementToken',
  baseUrl: 'https://projects.nortino.net/v1/',
  identity: '',
  createHoldingUser: 'User/CreateHoldingUser',
  CreateCompanyUser:'User/CreateCompanyUser',
  createSupervisorUser: 'User/CreateSupervisorUser',
  auth: 'Auth/Token',
  companyName:'companyName',
  CreateProject: 'Project/CreateProject',
  CreateActivity: 'Project/CreateActivity/',
  registerAllocationReport: 'Project/RegisterAllocationReport/',
  modifyDependentActivity: 'Project/ModifyDependentActivity/',
  showDependentActivities: 'Project/ShowDependentActivities/',
  allocationReportVerification: 'Project/AllocationReportVerification/',
  GetMyCompany: 'Company/GetMyCompany',
  CompanyModify: 'Holding/CompanyModify/',
  GetTargetsOfProject: 'Project/GetTargetsOfProject',
  getProjectsGeneralInfoOfCompany: 'Project/GetProjectsGeneralInfoOfCompany/',
  GetProjectGeneralPropertiesById: 'Project/GetProjectGeneralPropertiesById/',
  getProjectsWithDynamicFilter: 'Project/GetProjectsWithDynamicFilter/',
  RegisterProgressReport: 'Project/RegisterProgressReport/',
  ModifyWaterShedAndCanalsSpeceficDetail: 'Project/ModifyWaterShedAndCanalsSpeceficDetail/',
  ModifyRuralRoadSpeceficDetail: 'Project/ModifyRuralRoadSpeceficDetail/',
  ModifyKnowledgeBasedSpeceficDetail: 'Project/ModifyKnowledgeBasedSpeceficDetail/',
  ModifySocialTransformationSpeceficDetail: 'Project/ModifySocialTransformationSpeceficDetail/',
  ModifyRevivalIndustrySpeceficDetail: 'Project/ModifyRevivalIndustrySpeceficDetail/',
  ModifyGetHealthSpeceficDetail: 'Project/ModifyGetHealthSpeceficDetail/',
  GetCompaniesWithRegisterationStatus: 'Holding/GetCompaniesWithRegisterationStatus',
  UploadDocumentsOfProgressReport: 'Media/UploadDocumentsOfProgressReport/',
  GetProgressReports :'Project/GetProgressReports',
  GetAllocationReports:'Project/GetAllocationReports',
  ModifyProjectGeneralInfo:'Project/ModifyProjectGeneralInfo/',
  GetProgressReportsForSupervisor:'Project/GetProgressReportsForSupervisor/',
  GetAllocationReportsForSupervisor:'Project/GetAllocationReportsForSupervisor/',
  GetUsersWithDynamicFilter:'Holding/GetUsersWithDynamicFilter',
  CompanyInfo: 'CompanyInfo',
  userRole: 'userRole',
  RoleHome: 'RoleHome',
  showHierarchicalStructureActivities: 'Project/ShowHierarchicalStructureActivities/',
  showActivities: 'Project/ShowActivities/',
  ModifyProjectParticipant:'Project/ModifyProjectParticipant/',
  ModifyProjectResourceInformation:'Project/ModifyProjectResourceInformation/',
  UploadDocumentsOfProject: 'Media/UploadDocumentsOfProject/',
  SearchLocation: 'Region/SearchLocation',
  AllocationReportVerification: 'Project/AllocationReportVerification/',
  ProgressReportVerification: 'Project/ProgressReportVerification/',
  ComputeCompanyProjectProgress: 'Holding/ComputeCompanyProjectProgress',
  AmIAllowedToMakeThisClaim: 'Auth/AmIAllowedToMakeThisClaim/',
  GetItemOfRegions: 'Region/GetItemOfRegions',
  AssigneUserAsProjectSupervisor: 'Holding/AssigneUserAsProjectSupervisor/'
}
