export const url = {
  tokenName: 'progectManagementToken',
  baseUrl: 'https://projects.nortino.net/v1/',
  identity: '',
  createHoldingUser: 'User/CreateHoldingUser',
  CreateCompanyUser:'User/CreateCompanyUser',
  createSupervisorUser: 'User/CreateSupervisorUser',
  auth: 'Auth/Token',
  CreateProject: 'Project/CreateProject',
  CreateActivity: 'Project/CreateActivity',
  registerAllocationReport: 'Project/RegisterAllocationReport/',
  modifyDependentActivity: 'Project/ModifyDependentActivity/',
  showDependentActivities: 'Project/ShowDependentActivities/',
  allocationReportVerification: 'Project/AllocationReportVerification/',
  GetMyCompany: 'Company/GetMyCompany',
  CompanyModify: 'Holding/CompanyModify/',
  GetTargetsOfProject: 'Project/GetTargetsOfProject',
  getProjectsGeneralInfoOfCompany: 'Project/GetProjectsGeneralInfoOfCompany/',
  GetProjectGeneralPropertiesById: 'Project/GetProjectGeneralPropertiesById/',
  getProjectsWithDynamicFilter: 'Project/GetProjectsWithDynamicFilter/',
  RegisterProgressReport: 'Project/RegisterProgressReport/',
  ModifyWaterShedAndCanalsSpeceficDetail: 'Project/ModifyWaterShedAndCanalsSpeceficDetail/',
  ModifyRuralRoadSpeceficDetail: 'Project/ModifyRuralRoadSpeceficDetail/',
  ModifyKnowledgeBasedSpeceficDetail: 'Project/ModifyKnowledgeBasedSpeceficDetail/',
  ModifySocialTransformationSpeceficDetail: 'Project/ModifySocialTransformationSpeceficDetail/',
  ModifyRevivalIndustrySpeceficDetail: 'Project/ModifyRevivalIndustrySpeceficDetail/',
  ModifyGetHealthSpeceficDetail: 'Project/ModifyGetHealthSpeceficDetail/',
  GetCompaniesWithRegisterationStatus: 'Holding/GetCompaniesWithRegisterationStatus'
}
